### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by TakayasuNasu** [TakayasuNasu/FamousSpotTour#5]
UI
---

- [x] Setting 
    - [x] Get data from Firebase again

Register data to Firebase
---

- [x] Spot
- [x] Category
- [x] Tag
- [x] Spots-Tags
- [x] Image
- [x] Sub images
- [x] LastUpdateAt
- [x] Detail text
- [x] Headline text

Feature
---

### Splash

- [x] Show Splash image.
- [x] Show loading icon during connection to Firebase.
- [x] Get data from firebase.
- [x] Data insert using realm.
- [x] Truncate realm.

> Basically no connect except splash page.
Exception: Show Image, register Like and Dislike.

### TopViewController
- [x] Display category images and descriptions.
- [x] Move to MapView.
- [x] Send selected category number to MapView.

### MapViewController

- [x] Show pin and horizontal images of spots filtered by tag.
- [x] Show only one pin that when don't show horizontal list.
- [x] Move to DetailViewController when user tap horizontal list image.

### ListViewController

- [x] Show list of spots filtered by tag
- [x] Move to DetailViewController when user tap horizontal list image.

### DetailViewController

- [x] Show detail information.
- [x] Show number Like and Dislike.
- [x] Exchange achieved and unachieved.
- [ ] Set all data from Realm object when all columns are set up in Firebase.

### MyPageViewController

- [x] Show user avatar and name.
- [x] Show achieve rate with circle indicator.
- [x] Show Spots list that Like and Achieved.

### SettingViewController

- [x] Change avatar image.
- [x] Change name.
